/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/dogs/about.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DogCounter: typeof import('./src/components/dogs/DogCounter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListFilters: typeof import('./src/components/dogs/ListFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
