services:
 database:
   image: mysql   
   env_file: ./.env   
   environment:
     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
     MYSQL_DATABASE: $DB_NAME
   ports:
     - $DB_LOCAL_PORT:$DB_DOCKER_PORT   

 server:
   build: 
     context: .
     dockerfile: ./docker/nodejs/Dockerfile      
   volumes:     
      - .:/usr/src/app
      - /usr/src/app/node_modules
   ports:
    - "5000:5000"
   depends_on:
     - database

 frontend:
   build:
     context: ./frontend
     dockerfile: ../docker/frontend/Dockerfile      
   volumes:     
     - .:/usr/src/app/frontend
     - /usr/src/app/frontend/node_modules
   ports:
    - "5001:5001"
