services:

 database:
   image: mysql
   env_file: .env
   environment:
     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
     MYSQL_DATABASE: $DB_NAME
   ports:
     - $DB_LOCAL_PORT:80
   networks:
    dev_net:
     ipv4_address: 172.28.1.1

 backend:
   build:
     context: ./backend
     dockerfile: ../docker/backend/Dockerfile      
   volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
   ports:
    - "5000:80"       
   depends_on:
     - database
   networks:
     dev_net:
      ipv4_address: 172.28.1.2

 frontend:
   build:
     context: ./frontend
     dockerfile: ../docker/frontend/Dockerfile
   volumes:     
     - ./frontend:/usr/src/app
     - /usr/src/app/node_modules
   ports:
    - "5001:80"
   environment:
    - BACKEND_URL=http://backend:8000
   networks:
     dev_net:
      ipv4_address: 172.28.1.3

networks:
 dev_net:
  ipam:
   driver: default
   config:
    - subnet: 172.28.0.0/16

