services:

 database:
   image: mysql
   env_file: .env
   environment:
     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
     MYSQL_DATABASE: $DB_NAME
   ports:
     - $DB_LOCAL_PORT:$DB_DOCKER_PORT

 backend:
   build:
     context: ./backend
     dockerfile: ../docker/backend/Dockerfile      
   volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
   ports:
    - "5000:5000"   
    - "9229:9229"
   depends_on:
     - database

 frontend:
   build:
     context: ./frontend
     dockerfile: ../docker/frontend/Dockerfile
   volumes:     
     - ./frontend:/usr/src/app
     - /usr/src/app/node_modules
   ports:
    - "5001:8080"
