-- CreateTable
CREATE TABLE `TBL_DOGS` (
    `ID_DOG` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `SEX` VARCHAR(191) NOT NULL,
    `STERILIZED` BOOLEAN NOT NULL,
    `BIRTHDATE` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID_DOG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
