-- CreateTable
CREATE TABLE `TBL_PERROS` (
    `ID_PERRO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(191) NOT NULL,
    `SEXO` VARCHAR(191) NOT NULL,
    `ESTERILIZADO` BOOLEAN NOT NULL,
    `FECHA_NACIMIENTO` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID_PERRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
