-- CreateTable
CREATE TABLE `TBL_GENEROS_PELICULA` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TBL_PELICULAS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,
    `idGeneroPelicula` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TBL_PELICULAS` ADD CONSTRAINT `TBL_PELICULAS_idGeneroPelicula_fkey` FOREIGN KEY (`idGeneroPelicula`) REFERENCES `TBL_GENEROS_PELICULA`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
